config/routes.rb
Rails.application.routes.draw do
  # get '/teams', to: "teams#index"
  # get 'teams/new'
  root 'pages#home'
  devise_for :users
  resources :teams
  resources :projects

  # get '/team', to: "team#index"
  #resources :teams
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  #belongs_to :team
end

app/models/team.rb
class Team < ApplicationRecord
  #has_many :projects
  validates :name, presence: true
  validates :email, presence:true , length: { maximum:40 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:developer, :qa, :admin]
  after_initialize :set_default_role, :if => :new_record?
  def set_default_role
    self.role ||= :user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end
  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project
    else
      render :new, status: :unprocessable_entity
    end
  end
  def edit
    @project = Project.find(params[:id])
  end
  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to @project
    else
      render :edit, status: :unprocessable_entity
    end
  end
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path, status: :see_other
  end

  private
  def project_params
    params.require(:project).permit(:name, :description)

  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all

  end
  def show
    @team = Team.find(params[:id])
  end

  def new
    @team = Team.new
  end
  def create
    @team = Team.new(team_params)
    if @team.save
      redirect_to @team
    else
      render :new, status: :unprocessable_entity
    end
  end
  def edit
    @team = Team.find(params[:id])
  end
  def update
    @team = Team.find(params[:id])
    if @team.update(team_params)
      redirect_to @team
    else
      render :edit, status: :unprocessable_entity
    end
  end
  def destroy
    @team = Team.find(params[:id])
    @team.destroy
    redirect_to teams_path, status: :see_other
  end

  private
  def team_params
    params.require(:team).permit(:name, :email)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<% if current_user %>
  <%= link_to "Sign out", destroy_user_session_path, 'data-turbo-method': :delete %>
      <% if current_user.admin?%>
        <h1>hello <%= current_user.email %></h1>
        <p>you are <%= current_user.role %></p>
        <p>Create a Team: <%= link_to "Create", new_team_path%></p>






      <%elsif current_user.qa? %>
        <h1>hello <%= current_user.email %></h1>
        <p>you are <%= current_user.role %></p>
      <%else%>
        <h1>hello <%= current_user.email %></h1>
        <p>you are <%= current_user.role %></p>
      <% end %>
<% else %>
<h1>You are not signed in</h1>
<%= link_to "Sign Up", new_user_registration_path %>
<%= link_to "Login", new_user_session_path %>
<% end %>

app/views/projects/_form.html.erb
<%= form_with model: project do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true, autocomplete: "Project Name" %>
     <% project.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
      <% end %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description, autofocus: true, autocomplete: "Description" %>
     <% project.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
      <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Update Project</h1>

<%= render "form", project: @project %>

app/views/projects/index.html.erb
<%= link_to "Create New Project", new_project_path %>
<h1>All Project</h1>

<ul>
  <% @projects.each do |project| %>
    <li>
      <%= link_to project.name, project%>
    </li><br>
  <% end %>
</ul>

app/views/projects/new.html.erb
<h1>Create New Project</h1>

<%= render "form", project: @project %>

app/views/projects/show.html.erb
<%= link_to "Create New Project", new_project_path %>
<h1>All Projects</h1>

<h1><%= @project.name%></h1>
<p><%=@project.description%></p>
<ul>
  <li><%= link_to "Edit", edit_project_path(@project) %></li>
  <li><%= link_to "Destroy", project_path(@project), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>